
osx_image: xcode6.4
language: objective-c

before_install:
    - gem install cocoapods #--pre --quiet
    - pod --version
    - pod setup --silent
    - pod repo update --silent

script:
    - pod lib lint --allow-warnings # Prevent GPUImage warnings from breaking lint 
    - cd Demo
    - pod update
    - xctool -workspace PickerDemo.xcworkspace -scheme 'PickerDemo' -configuration Release -sdk iphonesimulator -arch i386 build
