title: NBUImagePicker
description: Modular and fully customizable UIImagePickerController replacement with Simulator-compatible AVFondation camera, AssetsLibrary and custom directory assets' browser, and image cropping, filters and gallery.
google_analytics: UA-40888254-5
show_downloads: true
theme: jekyll-theme-minimal

gems:
  - jekyll-mentions
